// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAJ3osKuqRMNIzncFA1sT_Ln4DnGZ0_ws',
    appId: '1:764357971556:web:d16da3b6b43d75e9ab1971',
    messagingSenderId: '764357971556',
    projectId: 'plantist-case-app',
    authDomain: 'plantist-case-app.firebaseapp.com',
    storageBucket: 'plantist-case-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVpAqPnBHPp3aj3ho4Bmpu0jSugDZZj0s',
    appId: '1:764357971556:android:ff03d66b763b3456ab1971',
    messagingSenderId: '764357971556',
    projectId: 'plantist-case-app',
    storageBucket: 'plantist-case-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBghzap0GxSiBT81Z6cDVctUm2MStghmvU',
    appId: '1:764357971556:ios:3edc24bae8ea1abdab1971',
    messagingSenderId: '764357971556',
    projectId: 'plantist-case-app',
    storageBucket: 'plantist-case-app.appspot.com',
    iosBundleId: 'com.example.plantistCaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBghzap0GxSiBT81Z6cDVctUm2MStghmvU',
    appId: '1:764357971556:ios:3edc24bae8ea1abdab1971',
    messagingSenderId: '764357971556',
    projectId: 'plantist-case-app',
    storageBucket: 'plantist-case-app.appspot.com',
    iosBundleId: 'com.example.plantistCaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAJ3osKuqRMNIzncFA1sT_Ln4DnGZ0_ws',
    appId: '1:764357971556:web:37ea4d9a24523c9cab1971',
    messagingSenderId: '764357971556',
    projectId: 'plantist-case-app',
    authDomain: 'plantist-case-app.firebaseapp.com',
    storageBucket: 'plantist-case-app.appspot.com',
  );
}
